### ISSUE TITLE
Pop!_OS Dağıtımı İçin Kurulum

### ISSUE THREAD

**Issue by alpeerkaraca** [alaturka/linux#1]
alaturka/linux#2 talebinde bahsi geçen,
`curl -fsSL https://get.linux.alaturka.dev/classroom | sudo bash -s`
komutunu çalıştırdığımıda 'Unsupported OS: debuntu' çıktısını alıyorum ve kurulum çalışmıyor. Ubuntu ve Debian dağıtımları dışında Pop!_OS dağıtımını desteklenen dağıtımlara ekleyebilir misiniz?

Sistem Özellikleri:
OS: Pop!_OS 21.10 x86_64
Kernel: Linux 5.16.11-76051611-generic
CPU: 16 x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
![Screenshot from 2022-03-10 23-02-48](https://user-images.githubusercontent.com/74460407/157745355-253257fe-b705-48da-9524-926ab5acb773.png)

**Comment by roktas** [comment]
Hata mesajında "hata" vardı düzelttim.  Classroom'u şimdilik sadece Ubuntu varsayımıyla hazırladım.  (Kişisel olarak tüm makinelerimde kurulu olan) Debian için bile düzenleme yapmadım.  Yani çalışabilir de çalışmayabilir de...  Buna gelecekte bakacağım (birinci önceliğim değil).  Kullandığın `Pop!_OS` için `/etc/os-release` dosyasının içeriğini yapıştırabilir misin buraya?  Bir kontrol edeyim, gerekirse bir "force" switch ekleyeceğim (sorumluluk size ait olarak).

**Comment by roktas** [comment]
@alpeerkaraca İş kaydını bu depoya alıyorum, doğru yeri burası olduğundan.

**Comment by roktas** [comment]
Şöyle dene:

```sh
curl -fsSL https://get.linux.alaturka.dev/classroom | sudo bash -s -- -relax
```

**Comment by alpeerkaraca** [comment]
**os-release dosyasının dökümü:**

`NAME="Pop!_OS"
VERSION="21.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.10"
VERSION_ID="21.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=impish
UBUNTU_CODENAME=impish
LOGO=distributor-logo-pop-os
`

Kurulum için verilen son komutu(`curl -fsSL https://get.linux.alaturka.dev/classroom | sudo bash -s -- -relax`) çalıştırdığımda verilen hata: `unable to locate  package 7zip` fakat sistemimde p7ip-full, p7zip-rar, p7zip, p7zip-desktop(snap sürümü) kurulu.

**Comment by roktas** [comment]
@alpeerkaraca İşte bu tür farkların yönetilmesi gerekiyor (ve çok zaman alıyor) :-/  `wontfix` yapmadan önce bakacağım buna, maliyeti fazla olmayacaksa bir düzenleme yaparım.

**Comment by roktas** [comment]
Buna baktım.  Alernatiflerini bırakıp 7zip'i seçmemin nedeni bu paketin geleceğe yönelik olarak daha standart olması.  Paket nispeten yeni, 2021 ortasında depolara girmiş.  7zip, Ubuntu Jammy (Mayıs ayında duyurulacak olan Ubuntu LTS) Universe depolarında bulunuyor.  Jammy depolarını bir şekilde Pop!_OS'a tanıtmalısın zaten, bu aşamada sorun olmaz başka aşamada sorun olur.  Pop!_OS [dokümanlarına](https://apt.pop-os.org/) göre şöyle yapabiliyor olman lazım:

```sh
add-apt-repository "deb [arch=amd64] http://apt.pop-os.org/staging-ubuntu/master jammy main multiverse restricted universe"
```

Listede `universe` mutlaka olmalı, bu var diğerlerinden biri (ör. `multiverse`) yoksa olmayanı çıkartırsın.

P.S. Pop!_OS Jammy paketleri: https://apt.pop-os.org/staging-ubuntu/master/dists/jammy/

**Comment by roktas** [comment]
Hmm, https://apt.pop-os.org/staging-ubuntu/master/dists/jammy/ linkine göre sadece main var.  Universe ekli olmayacak bu durumda (yine de dene).  Bu denemenin hatırına şu an aktif olarak kullanılmadığından `next` dalında `7zip` yerine `unzip` ve `xz-utils` paketlerini ekleyeceğim.  Universe'in olmaması önemli bir sıkıntı fakat.

**Comment by roktas** [comment]
`next` dalında düzenleme yaptım, bunu deneyelim bakalım.  Şöyle:

```sh
sudo add-apt-repository "deb http://apt.pop-os.org/ubuntu $(lsb_release -cs) main multiverse restricted universe" ||:
sudo add-apt-repository "deb [arch=amd64] http://apt.pop-os.org/staging-ubuntu/master jammy main" ||: # universe olmadığından
curl -fsSL https://next.linux.alaturka.dev/classroom | sudo bash -s -- -relax
```

P.S: Copy/paste yaparak al bunları terminale, yazmaya çalışma,  @alpeerkaraca bir de lütfen dönüşler biraz daha seri olsun, daha cevval olun, çok yavaşsınız :-)

**Comment by alpeerkaraca** [comment]
Vermiş olduğunuz iki repo'yu eklediğimde Release dosyaları bulunmadığına dair hata alıyorum bu sebeple update ve install komutları çalışmıyor. İlk olarak `sudo add-apt-repository "deb http://apt.pop-os.org/ubuntu $(lsb_release -cs) main multiverse restricted universe"` çalıştırdığımda 
`Err:11 http://apt.pop-os.org/ubuntu impish Release
  404  Not Found [IP: 52.38.47.2 80]`

`E: The repository 'http://apt.pop-os.org/ubuntu impish Release' does not have a Release`

`N: Updating from such a repository can't be done securely, and is therefore disabled by default.` çıktılarını alıyorum.

İkinci depoda ise sıkıntı yok.  Update çıktım: 
![updateCiktisi](https://user-images.githubusercontent.com/74460407/157881089-5e4f0491-cbcc-4939-9f10-5c3acc87e095.png)

Hata oluşturan depoyu kaldırıp kuruluma devam ettim ve `classroom -verbose install ` ile kurulumu çalıştırdım aldığım çıktı ise bu kez Unsupported Distribution : pop 
Ekran Görüntüsü:
![sonCikti](https://user-images.githubusercontent.com/74460407/157881926-6086f8f0-567a-4492-aaa2-5eaea5ddc9a3.png)

P.S: Hocam kusura bakmayın ders vakitlerime denk geldiği için sabahları hemen cevap veremiyorum. :/

**Comment by roktas** [comment]
Hmm, son aldığın hata Javascrip kurulumunda yaptığım Ubuntu kabulunden kaynaklanıyor, onu çözerim.

**Comment by roktas** [comment]
@alpeerkaraca javascript kurulumuna `pop` os ekledim (WIP), kurulumu tekrar edelim:

```sh
curl -fsSL https://next.linux.alaturka.dev/classroom | sudo bash -s -- -relax
```

Bakalım nerede takılacak :-)

**Comment by alpeerkaraca** [comment]
Aynı yerde hata verdi tekrardan. Javascript kısmında hata verip `unsupported distribution: pop` çıktısını veriyor.
![son](https://user-images.githubusercontent.com/74460407/157891408-b87110e0-f198-4297-8b0f-8c1b1a938818.png)

**Comment by roktas** [comment]
`classroom install` main dalından çalışır, verdiğim curl komutunu kullan, o next dalında

**Comment by roktas** [comment]
Öncesinde `rm -rf /opt/alaturka/linux` gerekebilir (bunu yapmadan dene önce, olmazsa bunu yap tekrar et)

**Comment by alpeerkaraca** [comment]
/opt/alaturka/linux dizinini silip curl komutunu çalıştırdım. Aldığım çıktı: 
![curl](https://user-images.githubusercontent.com/74460407/157893829-a4de4254-e109-4529-847e-5f086f66bcd1.png)

**Comment by roktas** [comment]
Pardon komutu hatalı vermişim şöyle yapacağız:

```sh
curl -fsSL https://next.linux.alaturka.dev/classroom | sudo bash -s -- -relax -branch next
sudo classroom -verbose install
```

**Comment by alpeerkaraca** [comment]
Sanırım kurulum tamamlandı hocam. En son /opt/alaturka/linux dizinini silip denediğimde verdiğiniz komutta çalışmadı ben de /usr/bin'de bulunan classroom dosyasını silip tekrar çalıştırdım ve kurulum baştan başladı ardından aşağıdaki listede bulunan yüklemeleri yaptı.

- base/core
- runtime/database
- runtime/javascript
- runtime/python
- runtime/ruby
- development/bash
- development/c
- development/database
- development/github
- development javascript
- development python
- development/ruby
- user/bash
- user/direnv
- user/mc
- user/neofetch
- user/neovim
- user/self
- user/tmux

**Comment by roktas** [comment]
> En son /opt/alaturka/linux dizinini silip denediğimde verdiğiniz komutta çalışmadı ben de /usr/bin'de bulunan classroom dosyasını silip tekrar çalıştırdım

Evet orda sorun bekliyordum ve yazacaktım aslında.  Neyse bu kurulumu daha sağlam hale getireceğim zaten.

Sistemi bir kontrol et, tmux çalışyoru mu(ctrl-a ile yeni pencere aç vs) ruby, node, python, gcc vs yerli yerinde mi falan.  Bir de açılış ekran'ı (Pop!_OS) eklersen güzel olur.  Her şey tamamsa bir düzenleme daha yapıp main'a alacağım bunu.

**Comment by roktas** [comment]
Pop!_OS'un switch kullanmadan boot edilmesine izin verdim (değişiklik main'da). `--relax` anahtarını da `--anyos` olarak değiştirdim (`Pop!_OS` için artık kullanman gerekmiyor).

**Comment by alpeerkaraca** [comment]
Tmux ve diğer kurulan dosyaları test ettim hepsi sorunsuz çalışmakta.

**Comment by roktas** [comment]
Güzel.  Bu gece bir düzenleme daha yapıp #2'de önerdiğim komutu legalize edeceğim.  Artık (en azından) Ubuntu ve Pop!_OS gibi türevlerde tek komutla kurulum yapabileceksiniz (bu iş kaydında yapıldığı gibi 2 parçalı değil yani). 

```sh
curl -fsSL https://get.linux.alaturka.dev/classroom | sudo bash -s
```
