### ISSUE TITLE
Seçilen Linux dağıtımlarında kurulum desteği ekle

### ISSUE THREAD

**Issue by BunyaminAkdeniz** [alaturka/linux#2]
### Adım

1 (ön kurulum)

### Hata ekranı

Ubuntu işletim sistemini kullanıyorum. Derslik sayfasında linux dağıtımları için bir kurulum talimatı bulamadım. 
![Ekran görüntüsü 2022-03-09 10-26-50](https://user-images.githubusercontent.com/91963771/157393085-1cd86a0b-4ca3-4829-9507-458422dbbd00.png)

### Windows sürümü

```text
Intel® Core™ i5-10300H CPU @ 2.50GHz × 8  /  15,5 GB / 
Ubuntu 20.04.4 LTS / 64-bit / X11
```

**Comment by roktas** [comment]
Tüm parçaları hazır, fakat  test ve dokümante etmedim henüz.   Risk almak istersen aşağıdaki komutu dene :-)

```bash
curl -fsSL https://get.linux.alaturka.dev/classroom | sudo bash -s
```

**Comment by roktas** [comment]
@BunyaminAkdeniz iş kaydını bu depoya taşıdım, FYI.

**Comment by roktas** [comment]
Bu özellik eklendi.  Daha sonra dokümante etmek üzere şu komutu çalıştırman yeterli:

```sh
curl -fsSL https://get.linux.alaturka.dev/classroom | sudo bash -s
```

Dikkat!  Sadece Ubuntu ve Pop!_OS için test edildi.

**Comment by BunyaminAkdeniz** [comment]
Hocam sistem sıkıntısız bir şekilde çalışıyor. Ama küçük bir yerde takıldım. VS code içinde classroom terminaline nasıl erişeceğim. Dökümantasyonda ki videoda burayı wsl'e bağlıyoruz. Ben nereye bağlayacağım. Bir anlam karmaşası yaşadım :D

![image](https://user-images.githubusercontent.com/91963771/158029031-0f5d4c07-e402-401c-8d72-4d794b177504.png)

**Comment by roktas** [comment]
Gönderdiğin ekran görüntüsüne göre zaten terminaldesin :-)  Bir yere bağlaman gerekmiyor yani.  Classroom'u native olarak Linux'a (Ubuntu) kurduğunda WSL diye bir şeye gerek, o sadece Windows üzerinde anlamlı birşey.

**Comment by BunyaminAkdeniz** [comment]
Hocam kafamı lets grad komutu karıştırdı. Terminalim bu komuta cevap vermiyor ödev testini nasıl yapacağım ?

**Comment by roktas** [comment]
Cevap vermiyor derken?  Ekran görüntüsü atar mısın?  `lets` hiç mi bulunamıyor, yoksa bulunduğu dizini mi beğenmiyor?  Gönderdiğin ekran görüntüsündeki dizinde `lets` çalışmaz, ona gereken bulunduğu dizinin bir ödev deposu içinde olması.  Örneğin:

```sh
cd ~/github-classroom/19-22s-c-1
lets grad # hata verir
cd ~/github-classroom/19-22s-c-1/hello-world-BunyaminAkdeniz
lets grad # burada veya buradan itibaren bir alt dizinde çalışır, çünkü ödev deposundasın
```

**Comment by BunyaminAkdeniz** [comment]
Hiç bulmuyor... 

![image](https://user-images.githubusercontent.com/91963771/158030539-bc7c8c50-4652-4b77-9736-5db5b4019758.png)

**Comment by roktas** [comment]
Kurulumunda bir sıkıntı var bu durumda.  `lets` programı `/usr/bin/lets` dosya yolunda kurulu olmalıydı.

Kurulumu tekrar yapıp dener misin?

```sh
curl -fsSL https://get.linux.alaturka.dev/classroom | sudo bash -s -- -verbose -afresh
```

Hala sorun varsa kurulum ekranlarını parça parça göndermeni isteyeceğim.  Bir de hangi dağıtımdasın şu an, onu da yaz:

```sh
lsb_release -a
```

**Comment by roktas** [comment]
Aklımdayken...  Sen bu kurulumu bu iş kaydının en başında verdiğim komutla o zaman mı yaptın?  Yani kurulumun eski mi? 
 Eğer öyleyse kurulum zaten eksiktir, çünkü sonrasında ben epey bir düzenleme yaptım.  Durum buysa yukarıdaki komut yerine şunu çalıştır:

```sh
sudo classroom -verbose install
```

Bu sorunu çözmüyorsa diğer yolu (önceki mesaj) kullan.

**Comment by BunyaminAkdeniz** [comment]
Kurulumu ilk başta  `curl -fsSL https://get.linux.alaturka.dev/classroom | sudo bash -s -- -verbose -afresh` komutu ile gerçekleştirdim. Şimdi tekrar `curl -fsSL https://get.linux.alaturka.dev/classroom | sudo bash -s -- -verbose -afresh` komutunu çalıştırdım. 

Çıktılar: 
![image](https://user-images.githubusercontent.com/91963771/158031014-303f0dd9-6f75-4cc8-b118-e0ae603c45d7.png)

**Comment by BunyaminAkdeniz** [comment]
`sudo classroom -verbose install` komutunu da çalıştırdığım. Terminalimi kapatıp açtım. Doğru dizinde `lets grad` komutunu çalıştırdım. Durum aynı

**Comment by roktas** [comment]
Hata en altta, litecli bulunamamış ve kurulum tamamlanmamış.  Neden, çünkü biz Ubuntu Jammy’yi esas aldık. Bunu çözeriz, bir bakayım.

**Comment by roktas** [comment]
@BunyaminAkdeniz Bir kaç önemli [değişiklik](https://github.com/alaturka/linux/blob/main/CHANGELOG.md) yaptım.  Bu değişiklikler senin de sorunu çözüyor olmalı.  Ama taze kod olduğundan hata olma ihtimali var tabii.  Kurulumu tekrar et bakalım.

**Comment by roktas** [comment]
@BunyaminAkdeniz Yalnız bir konuyu not edeyim, eski bir Ubuntu sürümü ("focal") kullanıyorsun.  Örneğin bu hata "focal"da litecli paketinin bulunmamasından kaynaklanıyordu.  Paket kritik olmadığından yokluğunu ignore ettim, ama her zaman bunu yapamayabilirim.  Bu tür kurulumlarda belli kabuller yapmak zorundayız.  Benim kabulum (koda gömmemekle birlikte) Ubuntu Jammy idi.  Bir an önce sistemini güncelle: https://cdimage.ubuntu.com/daily-live/current/  Zaten 2020 Nisan gibi yayımlanacak bu sürüm ve LTS olacak.

**Comment by BunyaminAkdeniz** [comment]
Ben kurarken en stabil sürüm focal'di. Sistemimi güncelleyip kurulumu yapacağım.

**Comment by BunyaminAkdeniz** [comment]
Kurulumu tamamladım sistem sorunsuz bir şekilde çalışıyor. Yardımlarınız için çok teşekkür ederim.

![Ekran görüntüsü 2022-03-13 13-29-17](https://user-images.githubusercontent.com/91963771/158055387-8f8ddef9-c7a0-466b-8c0f-b3d11dc47e0f.png)
